<a href="https://colab.research.google.com/github/arddrasoni-commits/12_data_preprocessing_handling_missing_values/blob/main/experiment_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical 12
## Arddra Soni
## 25070123022
## ENTC A1
### UNIT 3
### To perform preprocessing on a dataset and dealing with missing values

In [ ]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'Q':[56,89, np.nan], 'W':[67, np.nan, np.nan],'E':[90,80,70]})
df1

      Q     W   E
0  56.0  67.0  90
1  89.0   NaN  80
2   NaN   NaN  70

In [ ]:
# Boolean function
df1.isna() # 'isna' is TRUE when given no. is NaN and FALSE when given no. is a number

       Q      W      E
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
# isna inverter
df1.notna()

       Q      W     E
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
#columnwise na values
df1.isna().sum()

Q    1
W    2
E    0
dtype: int64

In [ ]:
df1.dropna() #NaN Rows are dropped

      Q     W   E
0  56.0  67.0  90

In [ ]:
df1.fillna (value = 'DEFAULT')

       Q      W   E
0   56.0   67.0  90
1   89.0  FAHHH  80
2  FAHHH  FAHHH  70

In [ ]:
df1.fillna(df1.mean()) # mean values of columns are calculated

      Q     W   E
0  56.0  67.0  90
1  89.0  67.0  80
2  72.5  67.0  70

In [ ]:
import pandas as pd

data = {
    "Roll no.": [23,34,45,56,67],
    "Name": ["Slash","Shadow","Charlie","Whistle", "Tango"],
    "Age": [19,"-", 23,24,13],
    "Marks": [85, 90, "-",55,56],
    "Department":["Acoustics","Aerodynamics","ENTC","Navy Tech","Mastering"],
    "Admission_Date":["01-09-20", "02-04-23", "04-06-24", "06-12-12", "08-10-24"]
}

df=pd.DataFrame(data)
df

   Roll no.     Name Age Marks    Department Admission_Date
0        23    Slash  19    85     Acoustics       01-09-20
1        34   Shadow   -    90  Aerodynamics       02-04-23
2        45  Charlie  23     -          ENTC       04-06-24
3        56  Whistle  24    55     Navy Tech       06-12-12
4        67    Tango  13    56     Mastering       08-10-24

In [ ]:
df.to_csv("student_data.csv",index = np.False_)

In [ ]:
# Step 2: Replace '-' with NaN to mar missing values
df.replace("-",np.nan,inplace= True)

#convert columns to numeric where needed

df["Age"]= pd.to_numeric(df["Age"], errors = 'coerce')
df["Marks"]= pd.to_numeric(df["Marks"], errors = 'coerce')

''' when converting data like strings to datatime, if some values are invalid or cannot be converted
then instead of showing an error, it will replace these invalid values with NaT(Not a Time)'''
df

/tmp/ipykernel_294/538829010.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace= True)

   Roll no.     Name   Age  Marks    Department Admission_Date
0        23    Slash  19.0   85.0     Acoustics       01-09-20
1        34   Shadow   NaN   90.0  Aerodynamics       02-04-23
2        45  Charlie  23.0    NaN          ENTC       04-06-24
3        56  Whistle  24.0   55.0     Navy Tech       06-12-12
4        67    Tango  13.0   56.0     Mastering       08-10-24

In [ ]:
#Step 3: Display missing values
print("Missing Values")
print(df.isnull().sum()) #identifies all null/NaN values and sums it

Missing Values
Roll no.          0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
# Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(), inplace= True)

# Fill missing Marks with median
df["Marks"].fillna(df["Marks"].median(), inplace= True)

/tmp/ipykernel_294/1890726314.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace= True)
/tmp/ipykernel_294/1890726314.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace= True)

In [ ]:
# Step 5: Fix inconsistent text formatting

df["Department"] = df["Department"].str.upper()

In [ ]:
# Step 6: convert admission_date to standard date time format
df["Admission_date"] = pd.to_datetime(df["Admission_Date"], errors = 'coerce')

/tmp/ipykernel_294/4197517820.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Admission_date"] = pd.to_datetime(df["Admission_Date"], errors = 'coerce')

In [ ]:
# Step 7: Cleaned Data
print("Cleaned Data")
df

Cleaned Data

   Roll no.     Name    Age  Marks    Department Admission_Date Admission_date
0        23    Slash  19.00   85.0     ACOUSTICS       01-09-20     2020-01-09
1        34   Shadow  19.75   90.0  AERODYNAMICS       02-04-23     2023-02-04
2        45  Charlie  23.00   70.5          ENTC       04-06-24     2024-04-06
3        56  Whistle  24.00   55.0     NAVY TECH       06-12-12     2012-06-12
4        67    Tango  13.00   56.0     MASTERING       08-10-24     2024-08-10

In [ ]:
# Step 8: Save cleaned dataset
df.to_csv("cleaned_student_data.csv",index = False)

print("\nCleaned csv file saved as cleaned_student_data_.csv")

Cleaned csv file saved as cleaned_student_data_.csv

# IMPUTING MISSING VALUES

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [3]:
# Check Missing Values
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [4]:
#Inputing the missing value
df['Luggage.room'].mean()

np.float64(13.890243902439025)

In [5]:
df['Luggage.room'].median()

14.0

In [6]:
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())

In [7]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [8]:
df['Rear.seat.room'].mean()

np.float64(27.82967032967033)

In [9]:
df['Rear.seat.room'].median()

27.5

In [11]:
df['Rear.seat.room']=df['Rear.seat.room'].fillna(df['Rear.seat.room'].mean())

In [12]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [13]:
df['AirBags']=df['AirBags'].fillna(df['AirBags'].mode().values[0])
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [14]:
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [15]:
import pandas as pd

NewData = {
    "Fruits" : ["Apple","Banana","Mango","Grapes"],
    "Calories" : [420,380,"_",210],
    "Weight" : ["_",40,70,3],
    "Taste" : ["Sweet","Sweet","Sour","Sour"],
    "Price" : [70,40,"_",100],
    "DateOfPurchace" : ["2023-03-12","2020-01-06","03-01-2025","2026/02/12"]
}

df = pd.DataFrame(NewData)
print("Original DataFrame:")
df.to_csv("Fruits.csv",index=False)
print(df)

Original DataFrame:
   Fruits Calories Weight  Taste Price DateOfPurchace
0   Apple      420      _  Sweet    70     2023-03-12
1  Banana      380     40  Sweet    40     2020-01-06
2   Mango        _     70   Sour     _     03-01-2025
3  Grapes      210      3   Sour   100     2026/02/12

In [16]:
import numpy as np

df.replace("_",np.nan,inplace=True)
print(df)

   Fruits  Calories  Weight  Taste  Price DateOfPurchace
0   Apple     420.0     NaN  Sweet   70.0     2023-03-12
1  Banana     380.0    40.0  Sweet   40.0     2020-01-06
2   Mango       NaN    70.0   Sour    NaN     03-01-2025
3  Grapes     210.0     3.0   Sour  100.0     2026/02/12

/tmp/ipykernel_2150/84087974.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("_",np.nan,inplace=True)

In [17]:
df["Calories"]=pd.to_numeric(df["Calories"],errors="coerce")
df["Weight"]=pd.to_numeric(df["Weight"],errors="coerce")
df["Price"]=pd.to_numeric(df["Price"],errors="coerce")
print(df)

   Fruits  Calories  Weight  Taste  Price DateOfPurchace
0   Apple     420.0     NaN  Sweet   70.0     2023-03-12
1  Banana     380.0    40.0  Sweet   40.0     2020-01-06
2   Mango       NaN    70.0   Sour    NaN     03-01-2025
3  Grapes     210.0     3.0   Sour  100.0     2026/02/12

In [18]:
print(df.isnull().sum())

Fruits            0
Calories          1
Weight            1
Taste             0
Price             1
DateOfPurchace    0
dtype: int64

In [19]:
print(df["Calories"].fillna(df["Calories"].mean(),inplace=True))
print(df["Weight"].fillna(df["Weight"].median(),inplace=True))
print(df["Price"].fillna(df["Price"].mean(),inplace=True))

None
None
None

/tmp/ipykernel_2150/4269353898.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df["Calories"].fillna(df["Calories"].mean(),inplace=True))
/tmp/ipykernel_2150/4269353898.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df["Weight"].fillna(df["Weight"].median(),inplace=True))
/tmp/ipykernel_2150/4269353898.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df["Price"].fillna(df["Price"].mean(),inplace=True))

In [20]:
df["Fruits"] = df["Fruits"].str.upper()
df["Taste"] = df["Taste"].str.lower()
df

   Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12

In [21]:
print("Cleaned data : \n",df)
df.to_csv("CleanedData.csv",index=False)

Cleaned data :
    Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12